---
# task: main.yaml

# essential tasks
- name: creating devops group
  group: name=devops state=present
- name: create devops user
  user: name=devops comment="Devops User" uid=2001 group=devops
- name: install htop package
  action: apt name=htop state=present update_cache=yes

- name: install netcat package
  action: apt name=netcat state=present update_cache=yes


- name: disable apparmor
  service: name=apparmor state=stopped enabled=no
   
- name: uninstall apparmor
  action: apt name=apparmor state=absent   

- name: disable iptables
  service: name=iptables state=stopped enabled=no
  ignore_errors: yes

- include: ntp.yaml

########################

- name: Add user
  user: name=dil_barbosa comment="Danilo Barbosa" groups=sudo,devops append=yes
  

- name: Add public key
  authorized_key: user=dil_barbosa key="{{ lookup('file', 'public_keys/'+'dil_barbosa.pub') }}" state=present


- name: configure sudoers
  lineinfile:   dest=/etc/sudoers.d/ansible
                line="%devops ALL=(ALL) ALL"
                state=present
                create=yes
                validate='visudo -cf %s'




