---

- include: install/install.deb.yml
  when: ansible_os_family == 'Debian'

- name: Ensure mongodb is started
  service: name=mongod state=started enabled=true
  changed_when: False

- include: configure/configure.yml
