---

# task: install.yaml

# Install dependencies

- name: install Docker software dependencies
  apt: name=python-pip state=latest

- name: install docker-py
  pip: name=docker-py

- name: create directory on host
  file: path=/var/lib/registry state=directory mode=0755

roles:
  - docker
