---
galaxy_info:
  author: George Miroshnykov
  description: Manage MongoDB replica set
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
  - database
  - database:nosql
dependencies: []
