---

# Add an Apt signing key, uses whichever key is at the URL
- apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add repository
  apt_repository:  repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: install rabbitmq
  apt: name=rabbitmq-server state=latest update_cache=yes
