---
- name: updating OS
  apt: name=wget update_cache=yes

#- name: wget docker
#  get_url: url=https://get.docker.com dest=/tmp validate_certs=False

- name: get linux-image-extra
  apt: name=linux-image-extra-{{ ansible_kernel }} state=present

- name: delete lxc-docker
  apt: name=lxc-docker state=absent

#- name: get docker repo keys
#  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D
- name: get docker keys
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D


- name: add repository
  apt_repository:  repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: install docker
  apt: name=docker-engine state=latest update_cache=yes

- name: set gpasswd for ubuntu user
  shell: gpasswd -a ubuntu docker

- name: installing dependencies for pip
  apt: name=python-pip state=latest

- name: installing docker-compose
  pip: name=docker-compose state=latest
  notify: restart Docker service

- name: docker-compose version
  shell: docker-compose --version
  register: compose
  #debug: var=compose.stdout_lines

#file: src=/usr/bin/docker.io dst=/usr/local/bin/docker state=link
